### ISSUE TITLE
No INSTALL file as mentioned in description

### ISSUE THREAD

**Issue by carsato** [spk121/guile-curl#7]
Hello Mike.

No INSTALL file exist.
I supose the right instructions are http://www.lonelycactus.com/guile-curl.html.

Just for the record if someone else finds the same "problem" as me.

**Comment by carsato** [comment]
An answer to myself:
you have yo execute ./bootstrap first, then it'll appear.

**Comment by carsato** [comment]
Well, no way to install with guille-2.2 with my knowledge :( by the moment.

**Comment by carsato** [comment]
The sources in http://www.lonelycactus.com/guile-curl.html with it's INSTALL file are working.

**Comment by spk121** [comment]
Some versions of  guile.m4 lack the logic to allow finding guile-2.2.  When I make a tarball, I try to include a guile.m4 that works, but, since that is a manual step, I don't think my bootstrap script does it right.

I'll work on that when I get a chance.

**Comment by spk121** [comment]
Updated guile.m4 script
